#!/bin/bash
# increase/decrease granularity
GRANULARITY=5

case "${1}" in
  *up)
    pamixer --increase ${GRANULARITY}
    ;;
  *down)
    pamixer --decrease ${GRANULARITY}
    ;;
  *full)
    pamixer --set-volume 100
    ;;
  *zero)
    pamixer --set-volume 0
    ;;
  *mute)
    if [ `pamixer --get-mute` == "true" ]; then
      pamixer --unmute
    else
      pamixer --mute
    fi
    ;;
  # the following cases dont' need to update the status-bar;
  # therefore, they must explicitly exit;
  *get)
    pamixer --get-volume-human
    exit 0
    ;;
  *help | *)
    echo "${0##*/} modifies the Master volume level"
    echo "usage: ${0##*/} [get | up | down | full | zero | mute]"
    exit 0
    ;;
esac

sb_update volume # update volume module in status-bar
